import type { Metadata } from "next";
import {  Google_Sans } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const geistSans = Google_Sans({
  variable: "--font-googlesans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable}  h-full antialiased`}
    >
      <StoreProvider>
      <body className="min-h-full flex flex-col">{children}</body>
      </StoreProvider>
    </html>
  );
}